package com.app.idnbin.Assets.Base;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Digital {
    private List<String> time1 = Collections.singletonList("5:00-5:30");
    private List<String> time2 = Collections.singletonList("6:00-2:15");
    private List<String> time3 = Collections.singletonList("5:00-5:30 5:30-1:30");
    private List<String> time4 = Collections.singletonList("5:30-19:30");
    private List<String> time5 = Collections.singletonList("6:30-23:30");
    private List<String> time6 = Collections.singletonList("6:30-00:30");
    private List<String> time7 = Collections.singletonList("10:30-00:30");
    private List<String> time8 = Collections.singletonList("11:30-00:30");
    private ArrayList<String> multiplier1 = new ArrayList<>();

    private SymbolsData eurusd = new SymbolsData(true, true,"EUR/USD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURUSD.png?alt=media", "This shows how many US Dollars can be converted into one Euro. The US imports 10% of Eurozone's total exports, whereas Eurozone imports 19.2% of United States's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas the US' largest export components are machinery, nuclear reactor, boiler products and electrical/electronic equipment.","Digital");
    private SymbolsData usdjpy = new SymbolsData(false, true,"USD/JPY", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDJPY.png?alt=media", "This shows how many Japanese Yen can be converted into one United States Dollar. Japan imports 0.044 of the US total exports, whereas the US imports 0.22 of Japan's total exports. The largest component of the US exports are machinery, nuclear reactor and boiler products, whereas Japan's largest export components are vehicles other than railway, tramway.","Digital");
    private SymbolsData eurjpy = new SymbolsData(false, true,"EUR/JPY", time2, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Euro. Japan imports 1.6% of Eurozone's total exports, whereas Eurozone imports 11.5% of Japan's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Japan's largest export components are vehicles, machinery, nuclear reactor and boiler products.","Digital");
    private SymbolsData gbpjpy = new SymbolsData(false, true,"GBP/JPY", time3, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one  Pound sterling. Japan imports 1.1% of the UK's total exports, whereas the UK's imports 2.1% of Japan's total exports. The largest component of the UK's exports are machinery, nuclear reactor and boiler products, whereas Japan's largest export components are vehicles other than railway, tramway.","Digital");
    private SymbolsData audjpy = new SymbolsData(false, true,"AUD/JPY", time4, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDJPY-01.png?alt=media", "This shows how many United States Dollars can be converted into one Australian Dollar. The US imports 4.9% of Australia's total exports, whereas Australia imports 1.6% of the US total exports. The largest component of Australia's exports are ores slag and ash, whereas the US largest export components are machinery, nuclear reactor and boiler products.","Digital");
    private SymbolsData gbpusd = new SymbolsData(false, true,"GBP/USD", time5, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNOKJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Norwegian krone. Japan imports 1.2% of Norway’s total exports, whereas Norway imports 6.9% of Japan’s total exports. The largest component of Norway’s exports is mineral fuels, oils, ores slag and ash, whereas Japan's largest export components are Vehicles other than railway, tramway.","Digital");
    private SymbolsData eurgbp = new SymbolsData(false, true,"EUR/GBP", time6, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURGBP-01.png?alt=media", "This shows how many Pounds sterling can be converted into one Euro. The UK imports 20% of Eurozone's total exports, whereas Eurozone imports 55% of the UK total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas the UK's largest export components are gold and vehicles.","Digital");
    private SymbolsData eurchf = new SymbolsData(false, true,"EUR/CHF", time7, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURCHF-01.png?alt=media", "","Digital");
    private SymbolsData gbpchf = new SymbolsData(false, true,"GBP/CHF", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPCHF.png?alt=media", "This shows how many Swiss Francs can be converted into one Pound sterling. Switzerland imports 4.9% of the UK's total exports, whereas the UK imports 11.1% of Switzerland's total exports. The largest component of the UK's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Switzerland's largest export components are precious metals and pharmaceutical products.","Digital");
    private SymbolsData euraud = new SymbolsData(false, true,"EUR/AUD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURAUD.png?alt=media", "This shows how many Australian Dollars can be converted into one Euro. Australia imports 0.88% of Eurozone's total exports, whereas Eurozone imports 8.7% of Australia's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Australia's largest export components are ores, mineral fuels and oil products.","Digital");
    private SymbolsData cadjpy = new SymbolsData(false, true,"CAD/JPY", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCADJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Canadian Dollar. Japan imports 2.2% of Canada's total exports, whereas Canada imports 1.5% of Japan's total exports. The largest components of Canada's exports are Vehicles other than railway, tramway, whereas Japan's largest export components are Vehicles other than railway, tramway.","Digital");
    private SymbolsData usdcad = new SymbolsData(false, true,"USD/CAD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDCAD.png?alt=media", "This shows how many Canadian Dollars can be converted into one US Dollar. Canada imports 19% of the US total exports, whereas the US imports 76% of Canada's total exports. The largest component of the US exports is vehicles and machinery, whereas Canada's largest export components is vehicles and mineral fuels.","Digital");
    private SymbolsData gbpcad = new SymbolsData(false, true,"GBP/CAD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPCAD-01.png?alt=media", "This shows how many Canadian Dollars can be converted into one Pound sterling. Canada imports 1.5% of the UK's total exports, whereas the UK imports 3.3% of Canada's total exports. The largest component of the UK' exports is machinery and vehicles, whereas Canada's largest export components is vehicles and mineral fuels.","Digital");
    private SymbolsData gbpaud = new SymbolsData(false, true,"GBP/AUD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPAUD.png?alt=media", "This shows how many Australian Dollars can be converted into one Pound sterling. Australia imports 4.2% of the UK's total exports, whereas the UK imports 1.3% of Australia's total exports. The largest component of the UK's exports is machinery, whereas Australia's largest export components is ores slag and ash.","Digital");
    private SymbolsData gbpnzd = new SymbolsData(false, true,"GBP/NZD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPNZD.png?alt=media", "This shows how many New Zealand Dollars can be converted into Pound sterling. Australia imports 0.26% of the UK's total exports, whereas the UK imports 2.8% of Australia's total exports. The largest component of the UK's exports is machinery, whereas New Zealand's largest export components are dairy products, eggs, honey, edible products.","Digital");
    private SymbolsData eurcad = new SymbolsData(false, true,"EUR/CAD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURCAD-01.png?alt=media", "This shows how many Canadian Dollars can be converted into one Euro. Canada imports 0.98% of Eurozone's total exports, whereas Eurozone imports 8.5% of Canada's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Canada's largest export components are vehicles and oil products.","Digital");
    private SymbolsData audusd = new SymbolsData(false, true,"AUD/USD", time8, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDUSD.png?alt=media", "This shows how many United States Dollars can be converted into one Australian Dollar. The US imports 4.9% of Australia's total exports, whereas Australia imports 1.6% of the US total exports. The largest component of Australia's exports are ores slag and ash, whereas the US largest export components are machinery, nuclear reactor and boiler products.","Digital");

    private ArrayList<SymbolsData> digitallist = new ArrayList<>(Arrays.asList(eurusd, usdjpy, eurjpy, gbpjpy, audjpy, gbpusd, eurgbp,
            eurchf, gbpchf, euraud, cadjpy, usdcad, gbpcad, gbpaud, gbpnzd, eurcad, audusd));

    public ArrayList<SymbolsData> getDigitallist() {
        return digitallist;
    }
}
