package com.app.idnbin.Assets.Base;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class ETF {
    private List<String> time1 = Collections.singletonList("19:00-01:30");
    private List<String> multiplier1 = Collections.singletonList("x3x5x10x20");

    private SymbolsData twentyplus_year_treasury_bond_etf = new SymbolsData(true, true,"20+ Year Treasury Bond ETF", time1, multiplier1, "", "iShares 20+ Year Treasury Bond ETF is operated in the USA. This ETF tracks the investment results of an index composed of U.S. Treasury bonds, having as a rule of thumb that their remaining maturities to be greater than twenty years.","ETF");
    private SymbolsData china_large_cap_etf = new SymbolsData(false, true,"China Large-Cap ETF", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FChina%20Large-Cap%20ETF.png?alt=media", "iShares China Large-Cap ETF (FXI) is an exchange-traded fund that is traded in the USA. FXI  follows the FTSE China 50 Index, investing in large-cap stocks. The fund’s investments are concentrated in the financial, oil and gas, technology and communications sectors. The ETF uses a representative sampling indexing strategy, investing - at least 90% of its assets in the securities of the underlying index.","ETF");
    private SymbolsData consumer_discretionary_spdr = new SymbolsData(false, true,"Consumer Discretionary SPDR", time1, multiplier1, "", "Consumer Discretionary Select Sector SPDR Fund is an exchange-traded fund incorporated in the USA. The ETF tracks the performance of the Consumer Discretionary Select Sector Index holding primarily large capitalization companies domiciled in the US. The ETF weights its holdings using a modified market cap approach, generally investing at least 95% of its assets in the index.","ETF");
    private SymbolsData core_msci_emerging_markets = new SymbolsData(false, true,"Core MSCI Emerging Markets", time1, multiplier1, "", "iShares Core MSCI Emerging Markets ETF traded in the USA. The ETF follows the MSCI Emerging Markets Investable Market Index which is designed to measure the emerging market equity performance. The ETF’s components consist of consumer discretionary, energy, financials and information technology companies.","ETF");
    private SymbolsData dow_jones_industrial_average_etf = new SymbolsData(false, true,"Dow Jones Industrial Average ETF", time1, multiplier1, "", "iShares Core MSCI Emerging Markets ETF traded in the USA. The ETF follows the MSCI Emerging Markets Investable Market Index which is designed to measure the emerging market equity performance. The ETF’s components consist of consumer discretionary, energy, financials and information technology companies.","ETF");
    private SymbolsData etfmg_alternative_harvest = new SymbolsData(false, true,"ETFMG Alternative Harvest", time1, multiplier1, "", "The fund tracks the performance of the Prime Alternative Harvest Index, which in turns mirrors the performance of a group of companies that are involved in the legal production and distribution of medical and recreational cannabis-based drugs and products.","ETF");
    private SymbolsData energy_spdr = new SymbolsData(false, true,"Energy SPDR", time1, multiplier1, "", "Energy Select Sector SPDR Fund is an exchange-traded fund traded in the USA. The ETF follows the performance of the Energy Select Sector Index. The ETF holdings consist of large-cap U.S. energy stocks. Particularly, it invests in companies that develop and produce crude oil and natural gas, provide drilling and other energy-related services. The holdings rebalance at regular intervals based on the market capitalization.","ETF");
    private SymbolsData gold_miners_etf = new SymbolsData(false, true,"Gold Miners ETF", time1, multiplier1, "", "VanEck Vectors Gold Miners ETF is an exchange-traded fund traded in the USA. The ETF tries to mimic the performance of the NYSE Arca Gold Miners Index. The major holdings of the ETF are materials stocks of all cap sizes across the globe with its largest allocation being in North American companies, especially those based in Canada. The ETF apply its rebalancing strategy based on the market capitalization.","ETF");
    private SymbolsData msci_emerging_markets_etf = new SymbolsData(false, true,"MSCI Emerging Markets ETF", time1, multiplier1, "", "iShares MSCI Emerging Markets ETF (EEM) is an ETF traded in the USA. This ETF tracks the performance of the MSCI TR Emerging Markets Index.  Particularly, the ETF holds emerging market stocks that are mainly classified as large and mid-cap. EEM weights the holdings using a market capitalization methodology and rebalances quarterly.","ETF");
    private SymbolsData msci_japan_etf = new SymbolsData(false, true,"MSCI Japan ETF", time1, multiplier1, "", "iShares MSCI Japan ETF is incorporated in the USA. The ETF's target is to provide investment results that correspond to the performance of the Japanese market that is measured by the MSCI Japan Index. The ETF invests in a representative sample of index stocks, using a market capitalization weighted method.","ETF");
    private SymbolsData msci_mexico_etf = new SymbolsData(false, true,"MSCI Mexico ETF", time1, multiplier1, "", "iShares MSCI Mexico ETF is operated in the USA. The ETF aims to provide investment results that correspond to the performance of the MSCI Mexico IMI 25/50 Index. The fund invests in Mexican companies that make up Mexico’s stock market index but with different weights due to certain limitations.","ETF");
    private SymbolsData materials_select_sector_spdr = new SymbolsData(false, true,"Materials Select Sector SPDR", time1, multiplier1, "", "Materials Select Sector SPDR Trust is an exchange-traded fund operated in the USA. The Fund's investment results correspond to the performance of the Materials Select Sector Index. This Index consists of companies from chemicals, construction materials, containers and packaging industries.","ETF");
    private SymbolsData oil_services_etf = new SymbolsData(false, true,"Oil Services ETF", time1, multiplier1, "", "VanEck Vectors Oil Services ETF incorporated in the USA. The Fund tracks the performance results of the MVIS US Listed Oil Services 25 Index. This Index includes common stocks and depositary receipts of U.S. companies in the oil services sector.","ETF");
    private SymbolsData s_and_p_500_etf = new SymbolsData(false, true,"S&P 500 ETF", time1, multiplier1, "", "SPY is one of the largest and most popular ETF in the world as it tracks the S&P 500 Index. Managed by State Street Global Advisors, it offers the total return of the Index, before expenses. SPY has managed to become an exceedingly favoured fund with traders, as it toggles between risky and safe assets.","ETF");
    private SymbolsData s_and_p_metals_and_mining_etf = new SymbolsData(false, true,"S&P Metals & Mining ETF", time1, multiplier1, "", "SPDR S&P Metals & Mining ETF is incorporated in the USA. The Fund aims to replicate as closely as possible the performance of the S&P Metals & Mining Select Industry Index.","ETF");
    private SymbolsData s_and_p_oil_and_gas_explore_and_product = new SymbolsData(false, true,"S&P Oil & Gas Explor & Product", time1, multiplier1, "", "SPDR S&P Oil & Gas Exploration & Production ETF is incorporated in the USA. This Fund's objective is to replicate as closely as possible the S&P Oil & Gas Exploration & Production Select Industry Index, an equal-weighted index.","ETF");
    private SymbolsData semiconductor_etf = new SymbolsData(false, true,"Semiconductor ETF", time1, multiplier1, "", "VANECK Vectors Semiconductor is an ETF operated in the USA. The Fund tracks the performance results of the MVIS US Listed Semiconductor 25 Index. The fund invests in the largest and most liquid companies listed in the US, which are active in the semiconductor sector. The ETF has a rule of thumb to not hold more than 20% in any one security.","ETF");
    private SymbolsData technology_spdr = new SymbolsData(false, true,"Technology SPDR", time1, multiplier1, "", "Technology Select Sector SPDR Fund is an exchange-traded fund incorporated in the USA. The ETF tracks the performance of The Technology Select Sector Index. The ETF holds large and mid-cap technology stocks. Its largest investment allocation is in the United States. The ETF weights the holdings using a market capitalization methodology.","ETF");
    private SymbolsData us_real_estate_etf = new SymbolsData(false, true,"US Real Estate ETF", time1, multiplier1, "", "iShares U.S. Real Estate ETF is an exchange-traded fund traded in the USA. The Fund aims to investment results that correspond to the performance of the Dow Jones U.S. Real Estate Index. The Fund investments primary in the real estate industry sector of the U.S. equity market.","ETF");
    private SymbolsData ultraPro_short_qqq = new SymbolsData(false, true,"UltraPro Short QQQ", time1, multiplier1, "", "ProShares UltraPro Short QQQ traded in the USA and seeks investment results which correspond to 300% the inverse of the daily performance of the NASDAQ-100 Index.","ETF");
    private SymbolsData ultraShort_qqq = new SymbolsData(false, true,"UltraShort QQQ", time1, multiplier1, "", "UltraShort QQQ ProShares is an exchange-traded fund operated in the USA. The Fund target is to earn as daily investment results 200% of the inverse (opposite)daily performance of the NASDAQ-100 Index.","ETF");
    private SymbolsData ultraShort_s_and_p_500 = new SymbolsData(false, true,"UltraShort S&P500", time1, multiplier1, "", "Proshares UltraShort S&P500 is incorporated in the USA, seeking daily investment results that correspond to 200% of the inverse (opposite) daily performance of the S&P 500 Index.","ETF");
    private SymbolsData utilities_spdr = new SymbolsData(false, true,"Utilities SPDR", time1, multiplier1, "", "SPDR SELECT SECTOR FUND is an exchange-traded fund traded in the USA. The Fund aims is to provide investment results that correspond to the performance of the Utilities Select Sector Index. The Index tracks communication services, electrical power providers, and natural gas distributors.","ETF");
    private SymbolsData ishares_russell_2000_etf = new SymbolsData(false, true,"iShares Russell 2000 ETF", time1, multiplier1, "", "iShares Russell 2000 ETF is an exchange-traded fund that is traded in the USA. This ETF follows the performance of the Russell 2000 Index Fund. Specifically, the ETF holds mid- and small-cap U.S. stocks. The ETF’s holdings are rebalanced annually based on market capitalization.","ETF");

    private ArrayList<SymbolsData> etflist = new ArrayList<>(Arrays.asList(twentyplus_year_treasury_bond_etf, china_large_cap_etf, consumer_discretionary_spdr, core_msci_emerging_markets,
            dow_jones_industrial_average_etf, etfmg_alternative_harvest, energy_spdr, gold_miners_etf, msci_emerging_markets_etf, msci_japan_etf, msci_mexico_etf,
            materials_select_sector_spdr, oil_services_etf, s_and_p_500_etf, s_and_p_metals_and_mining_etf, s_and_p_oil_and_gas_explore_and_product, semiconductor_etf,
            technology_spdr, us_real_estate_etf, ultraPro_short_qqq, ultraShort_qqq, ultraShort_s_and_p_500, utilities_spdr, ishares_russell_2000_etf));

    public ArrayList<SymbolsData> getETFlist() {
        return etflist;
    }
}
