package com.app.idnbin.Assets.Base;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class Forex {
    private List<String> time1 = Collections.singletonList("02:31 Monday - 02:30 Friday");
    private List<String> multiplier1 = Collections.singletonList("x50x100x200x300");
    private List<String> multiplier2 = Collections.singletonList("x50x100x200x300x500x1000");
    private List<String> multiplier3 = Collections.singletonList("x50x100x200x300x500");
    private List<String> multiplier4 = Collections.singletonList("x100");
    private List<String> multiplier5 = Collections.singletonList("x50x100");
    private List<String> multiplier6 = Collections.singletonList("x25x50x100");

    private SymbolsData usdjpy = new SymbolsData(true, true,"USD/JPY", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDJPY.png?alt=media", "This shows how many Japanese Yen can be converted into one United States Dollar. Japan imports 0.044 of the US total exports, whereas the US imports 0.22 of Japan's total exports. The largest component of the US exports are machinery, nuclear reactor and boiler products, whereas Japan's largest export components are vehicles other than railway, tramway.","Forex");
    private SymbolsData eurusd = new SymbolsData(false, true,"EUR/USD", time1, multiplier2, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURUSD.png?alt=media", "This shows how many US Dollars can be converted into one Euro. The US imports 10% of Eurozone's total exports, whereas Eurozone imports 19.2% of United States's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas the US' largest export components are machinery, nuclear reactor, boiler products and electrical/electronic equipment.","Forex");
    private SymbolsData usdchf = new SymbolsData(false, true,"USD/CHF", time1, multiplier2, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDCHF-01.png?alt=media", "This shows how many Swiss Francs can be converted into one US Dollar. Switzerland imports 9.0% of the US total exports, whereas the US imports 1.7% of Switzerland's total exports. The largest component of the US' exports are machinery, nuclear reactor and boiler products, whereas Switzerland's largest export components are pearls, precious stones, metals, coins.","Forex");
    private SymbolsData gbpusd = new SymbolsData(false, true,"GBP/USD", time1, multiplier3, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPUSD.png?alt=media", "This shows how many US Dollars can be converted into one Pound sterling. The US imports 15% of the UK's total exports, whereas the UK imports 3.9% of US' total exports. The largest component of the UK's exports is machinery, whereas the US' largest export components is machinery too.","Forex");
    private SymbolsData usdmxn = new SymbolsData(false, true,"USD/MXN", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDMXN-01.png?alt=media", "This shows how many Mexican Pesos can be converted into one US Dollar. Mexico imports 16% of the US' total exports, whereas the US imports 80% of Mexico’s total exports. The largest component of the US' exports is vehicles and machinery, whereas Mexico’s largest export components is vehicles, electricals and electronic equipment.","Forex");
    private SymbolsData eurzar = new SymbolsData(false, true,"EUR/ZAR", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURZAR.png?alt=media", "This shows how many South African rands can be converted into one Euro. South Africa imports 0.76% of Germany’s total exports, whereas Germany imports 7.6% of South Africa’s total exports. The largest component of Germany's exports are vehicles, machinery, nuclear reactors and electricals, whereas South Africa's largest export components are precious stones and metals, vehicles and ores slag.","Forex");
    private SymbolsData usdpln = new SymbolsData(false, true,"USD/PLN", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDPLN-01.png?alt=media", "This shows how many Polish Zloty can be converted into one US Dollar. Poland imports 0.25% of the US' total exports, whereas the US imports 2.5% of Poland's total exports. The largest component of the US' exports is vehicles and machinery, whereas Poland's largest export components is machinery, nuclear reactors, boilers.","Forex");
    private SymbolsData usddkk = new SymbolsData(false, true,"USD/DKK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDDKK-01.png?alt=media", "This shows how many Danish Kroner can be converted into one US Dollar. Denmark imports 0.15% of the US total exports, whereas the US imports 5.2% of Denmark total exports. The largest component of the US exports are machinery, nuclear reactors, boilers, whereas Denmark's largest export components are vehicles other than railway, and tramway.","Forex");
    private SymbolsData eursgd = new SymbolsData(false, true,"EUR/SGD", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURSGD-01.png?alt=media", "This shows how many Singaporean Dollars can be converted into one Euro. Singapore imports 18% of Europe’s total exports, whereas Europe imports 10% of Singapore's total exports. The largest component of European exports is machinery and electrical and electronic equipment, whereas Singapore's largest export components is electricals and electronic equipment and machinery.","Forex");
    private SymbolsData usdhuf = new SymbolsData(false, true,"USD/HUF", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDHUF-01.png?alt=media", "This shows how many Hungarian forints can be converted into one US Dollar. Hungary imports 0.12% of the US total exports, whereas the US imports 2.8% of Hungary's total exports. The largest component of the US exports are machinery, nuclear reactors, boilers, whereas Hungary's largest export components are electricals, electronic equipment and machinery.","Forex");
    private SymbolsData sgdjpy = new SymbolsData(false, true,"SGD/JPY", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FSGDJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Singaporean dollar. Japan imports 4.8% of Singapore’s total exports, whereas Singapore imports 3.4% of Japan's total exports. The largest component of Singapore's exports are electrical, electronic equipment and machinery, whereas Japan's largest export components are vehicles, machinery and nuclear reactors.","Forex");
    private SymbolsData chfsgd = new SymbolsData(false, true,"CHF/SGD", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCHFSGD-01.png?alt=media", "This shows how many Singaporean dollars can be converted Swiss Franc. Singapore imports 2.5% of Switzerland total exports, whereas Switzerland imports 0.98% of Singapore's total exports. The largest component of Singapore's exports is electrical, electronic equipment, whereas Switzerland's largest export components are pearls, precious stones, metals, coins.","Forex");
    private SymbolsData usdrub = new SymbolsData(false, true,"USD/RUB", time1, multiplier6, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDRUB-01.png?alt=media", "This shows how many Russian Rubles can be converted into one US Dollar. Russia imports 2.9% of US' total exports, whereas the US imports 0.41% of Russia's total exports. The largest component of US' exports are Vehicles other than railway, tramway, whereas Russia's largest export components are Mineral fuels, oils, distillation products.","Forex");
    private SymbolsData audsgd = new SymbolsData(false, true,"AUD/SGD", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDSGD-01.png?alt=media", "This shows how many Singaporean dollars can be converted into one Australian Dollar. Singapore imports 1.9% of Australia’s total exports, whereas Australia imports 2.8% of Singapore’s total exports. The largest component of Australia's exports are mineral fuels, oils, ores slag and ash, whereas Singapore's largest export components are electricals and electronic equipment.","Forex");
    private SymbolsData eurdkk = new SymbolsData(false, true,"EUR/DKK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURDKK-01.png?alt=media", "This shows how many Danish kroner can be converted into one Euro. Denmark imports 1.4% of Germany’s total exports, whereas Germany imports 17% of Denmark’s total exports. The largest component of Germany’s exports are vehicles, machinery, nuclear reactors and electricals, whereas Denmark's largest export components are machinery, nuclear reactors and pharmaceuticals.","Forex");
    private SymbolsData eurnok = new SymbolsData(false, true,"EUR/NOK", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURNOK-01.png?alt=media", "This shows how many Norwegian Kroner can be converted into one Euro. The largest export component of Norway is mineral fuels, fish and other commodities. Germany, Netherlands and United Kingdom combined import 46% of Norway’s total exports.","Forex");
    private SymbolsData noksek = new SymbolsData(false, true,"NOK/SEK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNOKSEK-01.png?alt=media", "This shows how many Sweden Kroner can be converted into one Norwegian krone. Sweden imports 6.6% of Norway’s total exports, whereas Norway imports 10% of Sweden’s total exports. The largest component of Norway’s exports are mineral fuels, oils, ores slag and ash, whereas Sweden's largest export components are Machinery, nuclear reactors, boilers.","Forex");
    private SymbolsData nzdsgd = new SymbolsData(false, true,"NZD/SGD", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNZDSGD-01.png?alt=media", "This shows how many Singaporean Dollars can be converted into one New Zealand Dollar. Singapore imports 2.1% of New Zealand’s total exports, whereas New Zealand imports 0.5% of Singapore's total exports. The largest component of New Zealand’s exports are dairy products, eggs and honey, whereas Singapore’s largest export components are electricals and electronic equipment.","Forex");
    private SymbolsData usdsek = new SymbolsData(false, true,"USD/SEK", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDSEK.png?alt=media", "This shows how many Swedish Kroner can be converted into one US Dollar. Sweden imports 2.6% of the US' total exports, whereas the US imports 0.45% of Sweden's total exports. The largest component of the US' exports are machinery, nuclear reactor and boiler products, whereas Sweden's largest export components are also machinery, nuclear reactor and boiler products.","Forex");
    private SymbolsData usdnok = new SymbolsData(false, true,"USD/NOK", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDNOK-01.png?alt=media", "This shows how many Norwegian Kroner can be converted into one US Dollar. Norway imports 0.27% of the US' total exports, whereas the US imports 4.2% of Norway's total exports. The largest component of the US' exports are machinery, nuclear reactor and boiler products, whereas Norway's largest export components are mineral fuels, oils, distillation products.","Forex");
    private SymbolsData nokjpy = new SymbolsData(false, true,"NOK/JPY", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNOKJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Norwegian krone. Japan imports 1.2% of Norway’s total exports, whereas Norway imports 6.9% of Japan’s total exports. The largest component of Norway’s exports is mineral fuels, oils, ores slag and ash, whereas Japan's largest export components are Vehicles other than railway, tramway.","Forex");
    private SymbolsData eurmxn = new SymbolsData(false, true,"EUR/MXN", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURMXN-01.png?alt=media", "This shows how many Mexican pesos can be converted into one Euro. Mexico imports 1% of Germany’s total exports, whereas Germany imports 1.7% of Mexico’s total exports. The largest component of Germany’s exports are vehicles, machinery, nuclear reactors and electricals, whereas Mexico's largest export components are vehicles, electricals and electronic equipment.","Forex");
    private SymbolsData chfjpy = new SymbolsData(false, true,"CHF/JPY", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCHFJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Swiss Franc. Japan imports 1.3% of Switzerland 's total exports, whereas Switzerland imports 0.52% of Japan's total exports. The largest component of Switzerland 's exports is Pearls, precious stones, metals, coins, whereas Japan's largest export components is Vehicles other than railway, tramway.","Forex");
    private SymbolsData usdcad = new SymbolsData(false, true,"USD/CAD", time1, multiplier2, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDCAD.png?alt=media", "This shows how many Canadian Dollars can be converted into one US Dollar. Canada imports 19% of the US total exports, whereas the US imports 76% of Canada's total exports. The largest component of the US exports is vehicles and machinery, whereas Canada's largest export components is vehicles and mineral fuels.","Forex");
    private SymbolsData audchf = new SymbolsData(false, true,"AUD/CHF", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDCHF-01.png?alt=media", "This shows how many Swiss Francs can be converted into one Australian Dollar. Switzerland imports 0.44% of Australia's total exports, whereas the Australia imports 0.83% of Switzerland's total exports. The largest component of Australia's exports are Ores slag and ash, whereas Switzerland's largest export components are pearls, precious stones, metals, coins.","Forex");
    private SymbolsData audnzd = new SymbolsData(false, true,"AUD/NZD", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDNZD-01.png?alt=media", "This shows how many New Zealand Dollars can be converted into one Australian Dollar. New Zealand imports 3.6% of Australia’s total exports, whereas Australia imports 17% of New Zealand's total exports. The largest component of Australia’s exports is ores slag and mineral fuels, whereas New Zealand's largest export components is dairy, eggs and meat.","Forex");
    private SymbolsData nzdjpy = new SymbolsData(false, true,"NZD/JPY", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNZDJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one New Zealand Dollar. Japan imports 6.3% of New Zealand's total exports, whereas New Zealand imports 0.47% of Japan's total exports. The largest components of New Zealand's exports are dairy products, whereas Japan's largest export components are vehicles other than railway, tramway.","Forex");
    private SymbolsData nzdcad = new SymbolsData(false, true,"NZD/CAD", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNZDCAD-01.png?alt=media", "This shows how many Canadian Dollars can be converted into one New Zealand Dollar. New Zealand imports 1.3% of New Zealand's total exports, whereas New Zealand imports 0.091% of Canada's total exports. The largest components of New Zealand's exports are dairy products, whereas Canada's largest export components are mineral fuels, oils, distillation products.","Forex");
    private SymbolsData usdczk = new SymbolsData(false, true,"USD/CZK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FUSDCZK-01.png?alt=media", "This shows how many Czech Koruna can be converted into one US Dollar. Czech Republic imports 0.15% of the US total exports, whereas the US imports 2.1% of Czech Republic total exports. The largest component of the US exports are machinery, nuclear reactors, boilers, whereas China's largest export components are vehicles other than railway, and tramway.","Forex");
    private SymbolsData sekjpy = new SymbolsData(false, true,"SEK/JPY", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FSEKJPY-01.png?alt=media", "This shows how many Swedish Kroner can be converted into one Japanese Yen. Japan imports 1.5% of Sweden’s total exports, whereas Sweden imports 0.21% of Japan’s total exports. The largest component of Sweden’s exports are machinery, nuclear reactors, and boilers, whereas Japan's largest export components vehicles other than railway, tramway.","Forex");
    private SymbolsData nzdchf = new SymbolsData(false, true,"NZD/CHF", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNZDCHF-01.png?alt=media", "This shows how many Swiss Francs can be converted into one New Zealand Dollars. Switzerland imports 0.19% of New Zealand’s total exports, whereas New Zealand imports 0.072% of Switzerland's total exports. The largest component of New Zealand’s exports are dairy products, eggs and honey, whereas Switzerland's largest export components are pearls, precious stones and metal coins.","Forex");
    private SymbolsData cadnok = new SymbolsData(false, true,"CAD/NOK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCADNOK-01.png?alt=media", "This shows how many Norwegian Kroner can be converted into one Canadian Dollar. Norway imports 0.36% of Canada’s total exports, whereas Canada imports 1.2% of Norway’s total exports. The largest component of Canada’s exports are mineral fuels, oils and distillation products, whereas Norway’s largest export components are also mineral fuels, oils and fish.","Forex");
    private SymbolsData audsek = new SymbolsData(false, true,"AUD/SEK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDSEK.png?alt=media", "This shows how many Swedish kroner can be converted into one Australian Dollar. Sweden imports 0.12% of Australia’s total exports, whereas Australia imports 1.1% of Sweden’s total exports. The largest component of Australia's exports are mineral fuels, oils, ores slag and ash, whereas Sweden's largest export components are machinery, nuclear reactors and vehicles.","Forex");
    private SymbolsData chfnok = new SymbolsData(false, true,"CHF/NOK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCHFNOK-01.png?alt=media", "","Forex");
    private SymbolsData audusd = new SymbolsData(false, true,"AUD/USD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDUSD.png?alt=media", "This shows how many United States Dollars can be converted into one Australian Dollar. The US imports 4.9% of Australia's total exports, whereas Australia imports 1.6% of the US total exports. The largest component of Australia's exports are ores slag and ash, whereas the US largest export components are machinery, nuclear reactor and boiler products.","Forex");
    private SymbolsData audjpy = new SymbolsData(false, true,"AUD/JPY", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Australian Dollar. Japan imports 15% of Australia's total exports, whereas Australia imports 2.3% of Japan's total exports. The largest components of Australia's exports are ores slag and ash, whereas Japan's largest export components are vehicles other than railway, tramway.","Forex");
    private SymbolsData eurjpy = new SymbolsData(false, true,"EUR/JPY", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Euro. Japan imports 1.6% of Eurozone's total exports, whereas Eurozone imports 11.5% of Japan's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Japan's largest export components are vehicles, machinery, nuclear reactor and boiler products.","Forex");
    private SymbolsData euraud = new SymbolsData(false, true,"EUR/AUD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURAUD.png?alt=media", "This shows how many Australian Dollars can be converted into one Euro. Australia imports 0.88% of Eurozone's total exports, whereas Eurozone imports 8.7% of Australia's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas Australia's largest export components are ores, mineral fuels and oil products.","Forex");
    private SymbolsData nzdusd = new SymbolsData(false, true,"NZD/USD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FNZDUSD-01.png?alt=media", "This shows how many US Dollars can be converted into one New Zealand Dollar. The US imports 11% of New Zealand's total exports, whereas New Zealand imports 0.25% of United States's total exports. The largest component of New Zealand's exports is dairy products, whereas United States's largest export components is machinery.","Forex");
    private SymbolsData eurnzd = new SymbolsData(false, true,"EUR/NZD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURNZD-01.png?alt=media", "This shows how many New Zealand Dollars can be converted into one Euro. New Zealand imports 0.98% of Eurozone's total exports, whereas Eurozone imports 11% of New Zealand's total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas New Zealand's largest export components are dairy and meat products.","Forex");
    private SymbolsData eurchf = new SymbolsData(false, true,"EUR/CHF", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURCHF-01.png?alt=media", "This shows how many Swiss francs can be converted into one Euro. Switzerland imports 1.4% of European Union’s total exports, whereas the European Union imports the majority of Switzerland's total exports. The largest component of European Union’s exports is machinery and electrical, electronic equipment, whereas Switzerland's largest export components are pearls, precious stones and pharmaceuticals.","Forex");
    private SymbolsData cadjpy = new SymbolsData(false, true,"CAD/JPY", time1, multiplier5, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCADJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one Canadian Dollar. Japan imports 2.2% of Canada's total exports, whereas Canada imports 1.5% of Japan's total exports. The largest components of Canada's exports are Vehicles other than railway, tramway, whereas Japan's largest export components are Vehicles other than railway, tramway.","Forex");
    private SymbolsData audnok = new SymbolsData(false, true,"AUD/NOK", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAUDNOK-01.png?alt=media", "This shows how many Norwegian kroner can be converted into one Australian Dollar. Norway imports 0.03% of Australia’s total exports, whereas Australia imports 0.19% of Norway’s total exports. The largest component of Australia's exports are mineral fuels, oils, ores slag and ash, whereas Norway's largest export components are mineral fuels, oils, fish and aluminum.","Forex");
    private SymbolsData cadpln = new SymbolsData(false, true,"CAD/PLN", time1, multiplier4, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCADPLN-01.png?alt=media", "This shows how many Polish Zlotys can be converted into one Canadian Dollar. Poland imports 0.13% of Canada’s total exports, whereas Canada imports less than 0.1% of Poland’s total exports. The largest component of Canada’s exports are mineral fuels, oils and distillation products, whereas Poland’s largest export components are machinery, vehicles and electronic equipment.","Forex");
    private SymbolsData eurgbp = new SymbolsData(false, true,"EUR/GBP", time1, multiplier3, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEURGBP-01.png?alt=media", "This shows how many Pounds sterling can be converted into one Euro. The UK imports 20% of Eurozone's total exports, whereas Eurozone imports 55% of the UK total exports. The largest component of Eurozone's exports are machinery, nuclear reactor, boiler products and vehicles, whereas the UK's largest export components are gold and vehicles.","Forex");
    private SymbolsData gbpjpy = new SymbolsData(false, true,"GBP/JPY", time1, multiplier3, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FGBPJPY-01.png?alt=media", "This shows how many Japanese Yen can be converted into one  Pound sterling. Japan imports 1.1% of the UK's total exports, whereas the UK's imports 2.1% of Japan's total exports. The largest component of the UK's exports are machinery, nuclear reactor and boiler products, whereas Japan's largest export components are vehicles other than railway, tramway.","Forex");
    private SymbolsData cadchf = new SymbolsData(false, true,"CAD/CHF", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FCADCHF-01.png?alt=media", "This shows Swiss Francs can be converted into one Canadian Dollar. Switzerland imports 0.25% of Canada's total exports, whereas Canada imports 1.2% of Switzerland's total exports. The largest components of Canada's exports are Vehicles other than railway, tramway, whereas Switzerland's largest export components are Pearls, precious stones, metals, coins.","Forex");

    private ArrayList<SymbolsData> forexlist = new ArrayList<>(Arrays.asList(usdjpy,eurusd,usdchf,gbpusd,usdmxn,eurzar,usdpln,
            usddkk,eursgd,usdhuf,sgdjpy,chfsgd,usdrub,audsgd,eurdkk,eurnok,noksek,nzdsgd,usdsek,usdnok,nokjpy,
            eurmxn,chfjpy,usdcad,audchf,audnzd,nzdjpy,nzdcad,usdczk,sekjpy,nzdchf,cadnok,audsek,chfnok,audusd,
            audjpy,eurjpy,euraud,nzdusd,eurnzd,eurchf,cadjpy,audnok,cadpln,eurgbp,gbpjpy,cadchf));

    public ArrayList<SymbolsData> getForexlist() {
        return forexlist;
    }
}
