package com.app.idnbin.Assets.Base;


import java.util.Arrays;
import java.util.Collections;
import java.util.ArrayList;
import java.util.List;

public class Stocks {
    private List<String> time1 =  Collections.singletonList("19:00-01:30");
    private List<String> multiplier1 =  Collections.singletonList("x3x5x10x20");

    private SymbolsData amd = new SymbolsData(true, true,"AMD", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Famd.jpg?alt=media", "The company is an American multinational semiconductor company, that develops computer processors, graphics cards and related technologies for business and consumer markets.","Stocks");
    private SymbolsData ansys = new SymbolsData(false, true,"ANSYS", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fansys.png?alt=media", "The company designs professional software for engineers that simulates the interactions of all disciplines of physics, structural, vibration, fluid dynamics, heat transfer and electromagnetics.","Stocks");
    private SymbolsData accenture = new SymbolsData(false, true,"Accenture", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Faccenture.png?alt=media", "The company provides professional consultancy services in businesses in almost every major business sector. Its services evolve around boosting business performance, improving business strategy, marketing and other professional solutions.","Stocks");
    private SymbolsData activision_blizzard = new SymbolsData(false, true,"Activision Blizzard", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FActivation%20Blizzard.png?alt=media", "The company is a video game developer and publisher for various gaming platforms, including video game consoles, personal computers and mobile devices.","Stocks");
    private SymbolsData adobe_systems = new SymbolsData(false, true,"Adobe Systems", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fadobe.png?alt=media", "The company enables individuals and companies to design and deliver transformative digital experiences via the Adobe cloud platform that offers a plethora of the company's famous design applications like Photoshop, Illustrator, Lightroom and others.","Stocks");
    private SymbolsData apple = new SymbolsData(false, true,"Apple", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fapple.png?alt=media", "The company is the producer of the iconic smartphone, tablet and personal computing devices like the iPhone, iPad, MacBook, Apple TV and Watch. Moreover, the company offers a wide range of digital services and media content through its Apple store that complement its range of products.","Stocks");
    private SymbolsData autodesk = new SymbolsData(false, true,"Autodesk", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fautodesk.jpg?alt=media", "The company is an American multinational software corporation that makes software for the architecture, engineering, construction, manufacturing, media, and entertainment industries.","Stocks");
    private SymbolsData baidu = new SymbolsData(false, true,"Baidu", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbaidu.png?alt=media", "The company is a Chinese language internet search provider and the equivalent of Google in China.","Stocks");
    private SymbolsData cisco_systems = new SymbolsData(false, true,"Cisco Systems", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcisco_systems.png?alt=media", "The company is an American multinational technology conglomerate that develops, manufactures and sells networking hardware, telecommunications equipment and other high-technology services and products.","Stocks");
    private SymbolsData citrix_systems = new SymbolsData(false, true,"Citrix Systems", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcitrix company.jpg?alt=media", "The company is a software company that offers secure delivery of apps and data, as well as workspace services solutions and delivery networking products.","Stocks");
    private SymbolsData dropbox = new SymbolsData(false, true,"Dropbox", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdropbox.png?alt=media", "The company offers cloud based storage and file sharing services to its customers, in a user friendly interface that is both simple and highly functional.","Stocks");
    private SymbolsData f5_networks = new SymbolsData(false, true,"F5 Networks", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ff5networks.png?alt=media", "The company is a leading developer and provider of software defined application services.","Stocks");
    private SymbolsData facebook = new SymbolsData(false, true,"Facebook", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffacebook.png?alt=media", "The company owns the largest global online social media service that initially started off as an internal socializing platform for Harvard University. The company now also owns Instagram, WhatsApp and its well known Messenger application and Facebook App store.","Stocks");
    private SymbolsData fidelity_national_information_services = new SymbolsData(false, true,"Fidelity National Information Services", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffidelity.png?alt=media", "The company is a leading financial services group with a focus on retail and institutional banking, payments, asset and wealth management, risk and compliance, consulting and outsourcing solutions.","Stocks");
    private SymbolsData first_solar = new SymbolsData(false, true,"First Solar", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffirst_solar.png?alt=media", "The company is a leading American photovoltaic manufacturer of rigid solar panels.","Stocks");
    private SymbolsData fiserv = new SymbolsData(false, true,"Fiserv", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffiserv.png?alt=media", "The company is a technology solutions provider offering business customers integrated information management and electronic commerce systems and services","Stocks");
    private SymbolsData google = new SymbolsData(false, true,"Google", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgoogle.png?alt=media", "","Stocks");
    private SymbolsData ibm_corporation = new SymbolsData(false, true,"IBM Corporation", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fibm.png?alt=media", "","Stocks");
    private SymbolsData intel = new SymbolsData(false, true,"Intel", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fintel.png?alt=media", "The company is an American multinational semiconductor corporation and a world leader in the design and manufacturing of technologies and products that power the cloud, personal computers and the internet of things.","Stocks");
    private SymbolsData masterCard = new SymbolsData(false, true,"MasterCard", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmastercard.png?alt=media", "","Stocks");
    private SymbolsData micron_technology = new SymbolsData(false, true,"Micron Technology", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmicron.png?alt=media", "The company designs and manufactures memory that is used in everything from personal computers and smartphones to servers that power the cloud.","Stocks");
    private SymbolsData microsoft = new SymbolsData(false, true,"Microsoft", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmicrosoft.png?alt=media", "The company is a multinational technology company that develops, licenses and supports a range of software products, services and devices.","Stocks");
    private SymbolsData nvidia = new SymbolsData(false, true,"Nvidia", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fnvidia.png?alt=media", "The company is a global semiconductor corporation that designs graphics processing units for the gaming market, as well as system on a chip units for the mobile computing, automotive market and artificial intelligence market.","Stocks");
    private SymbolsData payPal = new SymbolsData(false, true,"PayPal", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fpaypal.png?alt=media", "The company is the creator of the most popular online payment system that holds more than 100 million active accounts in 25 different currencies.","Stocks");
    private SymbolsData qualcomm = new SymbolsData(false, true,"Qualcomm", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fqualcomm.png?alt=media", "The company is an international designer of semiconductor and telecommunication products like the Snapdragon series smartphone processors that are found in all high-end android powered smartphones.","Stocks");
    private SymbolsData slack = new SymbolsData(false, true,"Slack", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fslack.png?alt=media", "The company is involved in cloud based collaboration solutions and is the owner of the worldwide popular team collaboration software tool Slack.","Stocks");
    private SymbolsData snapchat = new SymbolsData(false, true,"Snapchat", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fsnapchat.png?alt=media", "The company owns the world-famous social application Snapchat that enables people to communicate through short videos and images known as a Snap.","Stocks");
    private SymbolsData spotify = new SymbolsData(false, true,"Spotify", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fspotify.png?alt=media", "The company is the creator of the synonymous popular music, podcast, and video streaming application that is available in personal computers, tablets, smartphones and other smart devices.","Stocks");
    private SymbolsData twitter_inc = new SymbolsData(false, true,"Twitter Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftwitter.png?alt=media", "Twitter, Inc. offers products and services for users, advertisers, developers and data partners. The Company's products and services include Twitter, Periscope, Promoted Tweets, Promoted Accounts and Promoted Trends. Its Twitter is a platform for public self-expression and conversation in real time. Periscope broadcasts can also be viewed through Twitter and on desktop or mobile Web browser. Its Promoted Products enable its advertisers to promote their brands, products and services, amplify their visibility and reach, and extend the conversation around their advertising campaigns. Promoted Accounts appear in the same format and place as accounts suggested by its Who to Follow recommendation engine, or in some cases, in Tweets in a user's timeline. Promoted Trends appear at the top of the list of trending topics for an entire day in a particular country or on a global basis. Its MoPub is a mobile-focused advertising exchange. Twitter Audience Platform is an advertising offering.","Stocks");
    private SymbolsData visa = new SymbolsData(false, true,"Visa", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fvisa.png?alt=media", "The company is a leading payment services provider that offers international electronic payment services in over 200 countries.","Stocks");
    private SymbolsData zoom_video_communications_inc = new SymbolsData(false, true,"Zoom Video Communications Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fzoom video.png?alt=media", "The company is an information technology firm that offers clients collaboration software solutions and other cloud based services.","Stocks");
    private SymbolsData salesforce_com = new SymbolsData(false, true,"Salesforce.com", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fsalesforce.png?alt=media", "The company is a leading provider of enterprise cloud computing solutions, with a focus on customer relationship management, or CRM.","Stocks");
    private SymbolsData juventus_football_club = new SymbolsData(false, true,"Juventus Football Club", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fjuvenus.png?alt=media", "The company is the owner of Juventus Football Club S.p.A., most commonly known as Juve, which is a professional Italian football club.","Stocks");
    private SymbolsData adidas = new SymbolsData(false, true,"Adidas", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fadidas.png?alt=media", "The company is a multinational corporation, that designs and manufactures sports shoes, clothing and accessories.","Stocks");
    private SymbolsData la_francaise_des_jeux_sa = new SymbolsData(false, true,"La Francaise Des Jeux Sa", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FLa%20francaise%20des%20jeux%20sa.png?alt=media", "The company is involved in lottery games and services and is owned by the French state.","Stocks");
    private SymbolsData marks_spencer = new SymbolsData(false, true,"Marks & Spencer", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmarks.png?alt=media", "The company is a British international retailer that sells clothing, food and home products through its stores around the world.","Stocks");
    private SymbolsData continental = new SymbolsData(false, true,"Continental", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcontinental.png?alt=media", "The company is an international manufacturer of car tires, chassis and safety components and interior systems for passenger and commercial vehicles.","Stocks");
    private SymbolsData pirelli = new SymbolsData(false, true,"Pirelli", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fpirelli.png?alt=media", "The company designs and manufactures premium quality tires for passenger and commercial vehicles including motorcycles and bicycles.","Stocks");
    private SymbolsData advance_auto_parts = new SymbolsData(false, true,"Advance Auto Parts", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fadvance_auto_part.png?alt=media", "The company is a leading automotive aftermarket parts provider in North America, serving both professional installers, or DIY, customers as well as independently-owned operators.","Stocks");
    private SymbolsData amazon = new SymbolsData(false, true,"Amazon", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Famazon.png?alt=media", "The company is the largest online retailer in the world offering products like books, music and electronics, cloud services, groceries and many more.","Stocks");
    private SymbolsData best_buy = new SymbolsData(false, true,"Best Buy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbestbuy.jpg?alt=media", "The company sells a variety of electronic products like smartphones, laptops, entertainment devices and appliances through its network of retail stores in the US, Canada and Mexico.","Stocks");
    private SymbolsData comcast_class_a = new SymbolsData(false, true,"Comcast - Class A", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcomcast.jpg?alt=media", "The company is an American global telecommunications conglomerate and the largest broadcasting and cable television company in the US by revenue.","Stocks");
    private SymbolsData d_r_horton = new SymbolsData(false, true,"D R Horton", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FDRHorton.png?alt=media", "The company is the largest home construction company in United States.","Stocks");
    private SymbolsData darden_restaurants = new SymbolsData(false, true,"Darden Restaurants", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdarden.png?alt=media", "The company is the owner of well known casual dining chains in North America like Olive Garden, LongHorn Steakhouse, Fine Dining and other.","Stocks");
    private SymbolsData discovery_class_a = new SymbolsData(false, true,"Discovery - Class A", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdiscovery.png?alt=media", "The company is the producer of well known documentaries and documentary channels like discovery, animal planet, investigation discovery and other.","Stocks");
    private SymbolsData disney = new SymbolsData(false, true,"Disney", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdisney.png?alt=media", "The company is a diversified multinational mass media entertainment corporation and the world’s second largest media conglomerate after Comcast.","Stocks");
    private SymbolsData ferrari = new SymbolsData(false, true,"Ferrari", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fferrari.png?alt=media", "Ferrari NV designs and manufactures sports cars. The Company offers new and used vehicles, warranty programs, financial support, and maintenance, as well as watches, apparels, earphones, caps, and other accessories. Ferrari markets its products worldwide.","Stocks");
    private SymbolsData general_motors = new SymbolsData(false, true,"General Motors", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgeneral_motors.png?alt=media", "The company designs, manufactures and markets cars, trucks, crossovers and automobile parts.","Stocks");
    private SymbolsData hasbro = new SymbolsData(false, true,"Hasbro", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fhasbro.png?alt=media", "The company is an international manufacturer of toys, games and other entertainment products.","Stocks");
    private SymbolsData manchester_united = new SymbolsData(false, true,"Manchester United", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmanchester.png?alt=media", "The company is the owner of the worldwide famous British professional sports club Manchester United.","Stocks");
    private SymbolsData mcdonalds = new SymbolsData(false, true,"McDonald's", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmcdonald.png?alt=media", "The company is a worldwide fast food chain that serves a locally relevant menu of food and drinks sold at various price points in over 100 countries.","Stocks");
    private SymbolsData mercadoLibre_inc = new SymbolsData(false, true,"MercadoLibre Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmercado.png?alt=media", "The company is the leader in online commerce across Latin America. The company's services include online shopping solutions, payment solutions, classified ads, online shops for sellers and many more.","Stocks");
    private SymbolsData netflix = new SymbolsData(false, true,"Netflix", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fnetflix.png?alt=media", "The company is an international leader in online streaming of movies, series, documentaries and proprietary productions, with presence in over 190 countries.","Stocks");
    private SymbolsData nike = new SymbolsData(false, true,"Nike", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fnike.png?alt=media", "The company is the famous \"swoosh\" branded international designer and manufacturer of athletic apparel and footwear.","Stocks");
    private SymbolsData pinterest_inc = new SymbolsData(false, true,"Pinterest Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fpinterest.png?alt=media", "The company owns the popular social platform Pinterest, that allows easy sharing of ideas, images, places, decorations and many more.","Stocks");
    private SymbolsData starbucks = new SymbolsData(false, true,"Starbucks", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fstarbucks.png?alt=media", "The company is a worldwide leader in roasting, marketing and retailing of premium coffee. The company sells handcrafted coffee, tea and other beverages and a variety of fresh food items through its stores.","Stocks");
    private SymbolsData tesla = new SymbolsData(false, true,"Tesla", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftesla.png?alt=media", "The company is an innovative manufacturer of full electric cars and superchargers. The company also sells solar power and energy storage products.","Stocks");
    private SymbolsData viacomCBS_inc = new SymbolsData(false, true,"ViacomCBS Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fviacommcbs.png?alt=media", "The company is an American multinational media conglomerate involved in the production of television programs, broadcasting and other media entertainment content related activities.","Stocks");
    private SymbolsData eBay = new SymbolsData(false, true,"eBay", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Febay.png?alt=media", "The company is a multinational online auction and shopping website, where customers can buy from other customers or businesses that are members in the company's e-commerce platform.","Stocks");
    private SymbolsData merck = new SymbolsData(false, true,"Merck", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmerck.jpg?alt=media", "The company is a German pharmaceutical company with operations in chemical and life sciences sectors.","Stocks");
    private SymbolsData abbVie = new SymbolsData(false, true,"AbbVie", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fabbvie.png?alt=media", "The firm is a research based bio-pharmaceutical company engaged in the discovery, development and marketing of pharmaceutical products.","Stocks");
    private SymbolsData abbott_labs = new SymbolsData(false, true,"Abbott Labs", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fabbott_labs.png?alt=media", "The company is an international health care corporation involved in the research and development of various diagnostic and related products.","Stocks");
    private SymbolsData align_technology = new SymbolsData(false, true,"Align Technology", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Falign.jpg?alt=media", "The company designs and manufactures health care related products in dental care and orthodontics.","Stocks");
    private SymbolsData allergan = new SymbolsData(false, true,"Allergan", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fallergan.jpg?alt=media", "The company is a multi-national specialty pharmaceutical corporation, engaged in the development, marketing and distribution of brand name pharmaceutical products, medical aesthetics, biosimilar and over-the-counter pharmaceutical products.","Stocks");
    private SymbolsData amgen = new SymbolsData(false, true,"Amgen", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAmgen.png?alt=media", "The company is a biotechnology firm that discovers and develops therapeutic treatment solutions in the areas of oncology, hematology, cardiovascular disease and neuroscience.","Stocks");
    private SymbolsData aurora_cannabis_inc = new SymbolsData(false, true,"Aurora Cannabis Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Faurora_cannabis.jpg?alt=media", "The company is involved in the production and distribution of medical grade cannabis.","Stocks");
    private SymbolsData bristol_myers_squibb = new SymbolsData(false, true,"Bristol-Myers Squibb", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbristol_myers_squibb.png?alt=media", "The company is a global pharmaceutical firm engaged in the discovery, development and licensing of biopharmaceutical products.","Stocks");
    private SymbolsData cvs_health = new SymbolsData(false, true,"CVS Health", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcvs health.png?alt=media", "The company is an integrated pharmacy healthcare corporation that offers pharmacy care services to the senior community through Omnicare.","Stocks");
    private SymbolsData canopy_growth_corp = new SymbolsData(false, true,"Canopy Growth Corp", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcanopy%20growth.png?alt=media", "The company is involved in the production and distribution of various grades of medical grade cannabis.","Stocks");
    private SymbolsData cronos_group_inc = new SymbolsData(false, true,"Cronos Group Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcronos.png?alt=media", "The company is involved in the production and distribution of medical grade cannabis and cannabis oil.","Stocks");
    private SymbolsData daVita = new SymbolsData(false, true,"DaVita", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdavita.png?alt=media", "A health care company and the largest in the kidney care market in the United States.","Stocks");
    private SymbolsData danaher = new SymbolsData(false, true,"Danaher", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdanaher.png?alt=media", "The company owns strong brands in the fields of designing, manufacturing, and marketing industrial and consumer products.","Stocks");
    private SymbolsData gw_pharmaceuticals_adr = new SymbolsData(false, true,"GW Pharmaceuticals ADR", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgw.png?alt=media", "The company is involved in the research and development of cannabinoid drugs for the treatment of pain caused by serious illnesses like cancer and other.","Stocks");
    private SymbolsData gilead_science = new SymbolsData(false, true,"Gilead Science", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgilead_sciences.png?alt=media", "A research-based bio-pharmaceutical company that discovers, develops and commercializes medicines in areas of unmet medical need.","Stocks");
    private SymbolsData medtronic = new SymbolsData(false, true,"Medtronic", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmedtronic.png?alt=media", "The firm is a medical technology and services company that develops, manufactures and markets its medical devices and technologies to hospitals, physicians, clinicians and patients in approximately 160 countries.","Stocks");
    private SymbolsData pfizer = new SymbolsData(false, true,"Pfizer", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fpfizer.png?alt=media", "The company is a research based bio-pharmaceutical firm involved in the discovery, development and manufacturing of healthcare products. It is among the world's largest pharmaceutical companies.","Stocks");
    private SymbolsData quest_diagnostics = new SymbolsData(false, true,"Quest Diagnostics", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fquest_diagnostics.png?alt=media", "An American health care company specialized in clinical laboratory services and products.","Stocks");
    private SymbolsData resmed_inc = new SymbolsData(false, true,"Resmed Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FResmed%20Inc.png?alt=media", "The company is engaged in the development, manufacturing and marketing of medical devices and cloud-based software applications that diagnose, treat and manage respiratory disorders.","Stocks");
    private SymbolsData stryker = new SymbolsData(false, true,"Stryker", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fstyker.png?alt=media", "The company is an international health care manufacturer of medical devices and equipment in the areas of orthopedics, surgical tools and neurologics.","Stocks");
    private SymbolsData teleflex_inc = new SymbolsData(false, true,"Teleflex Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fteleflex.png?alt=media", "A diversified company that provides medical technology products which the company designs, develops, manufactures and supplies to hospitals and healthcare providers for diagnostic and therapeutic procedures.","Stocks");
    private SymbolsData tilray_inc_class_2_common = new SymbolsData(false, true,"Tilray Inc - Class 2 Common", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftilray.png?alt=media", "The company is involved in the production and distribution of cannabis based drugs and products.","Stocks");
    private SymbolsData idexx_laboratories = new SymbolsData(false, true,"IDEXX Laboratories", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fidexx_laboratories.png?alt=media", "The company is a multinational developer, manufacturer and service provider of veterinary products and services.","Stocks");
    private SymbolsData easyJet = new SymbolsData(false, true,"easyJet", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Feasyjet.png?alt=media", "The company is a British budget airline carrier that operates in over 30 countries and 820 routes.","Stocks");
    private SymbolsData airbus_se = new SymbolsData(false, true,"Airbus SE", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAirbus.png?alt=media", "The company is a multinational corporation in the aerospace and defense industry that produces and designs commercial and military products like the double-deck A380 airbus commercial passenger airplane and the military Eurofighter Typhoon fighting plane.","Stocks");
    private SymbolsData siemens = new SymbolsData(false, true,"Siemens", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fsiemens.png?alt=media", "The company is an industrial conglomerate that manufactures power generation systems and industrial grade machinery among other products and systems.","Stocks");
    private SymbolsData boeing = new SymbolsData(false, true,"Boeing", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fboeing.jpg?alt=media", "The company is an industrial conglomerate in the aerospace and defense industry that designs and manufactures airplanes, rockets and satellites among other related products.","Stocks");
    private SymbolsData rolls_royce = new SymbolsData(false, true,"Rolls-Royce", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Frollsroyce.png?alt=media", "The company is a leading industrial manufacturer of aero-engines, large scale power generators and other industrial grade machinery.","Stocks");
    private SymbolsData m_company = new SymbolsData(false, true,"3M Company", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2F3m_company.png?alt=media", "The company is an international technology conglomerate manufacturing over 55,000 products. Among its most famous products is the \"Post-it\" stickers.","Stocks");
    private SymbolsData caterpillar = new SymbolsData(false, true,"Caterpillar", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcaterpillar.png?alt=media", "The company is a leading manufacturer of construction and mining machines under the iconic CAT brand.","Stocks");
    private SymbolsData cintas = new SymbolsData(false, true,"Cintas", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcintas.png?alt=media", "The company is a provider of corporate identity uniforms through rental and sales programs, as well as a provider of related business services.","Stocks");
    private SymbolsData delta_air_lines = new SymbolsData(false, true,"Delta Air Lines", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdelta_airlines.png?alt=media", "The firm is an airline corporation that provides scheduled air transportation for passengers and cargo throughout the United States and across the world.","Stocks");
    private SymbolsData expeditors = new SymbolsData(false, true,"Expeditors", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fexpeditors.png?alt=media", "The company is a provider of airfreight, ocean freight, customs clearance services and other solutions.","Stocks");
    private SymbolsData dover = new SymbolsData(false, true,"Dover", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdover.png?alt=media", "The company is an industrial manufacturer of specialized industrial equipment. This includes fuel and other fluid containers and fluid handling solutions, refrigerating systems and other engineered systems.","Stocks");
    private SymbolsData flowserve = new SymbolsData(false, true,"Flowserve", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fflowserve.png?alt=media", "The company is an industrial manufacturer of flow control systems like pumps, valves, seals and other related products and services.","Stocks");
    private SymbolsData fortune_brands_home_and_security = new SymbolsData(false, true,"Fortune Brands Home & Security", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FFortune%20Brands%20Home%20%26%20Security.png?alt=media", "The company is an American manufacturer of home fixtures and hardware.","Stocks");
    private SymbolsData general_electric = new SymbolsData(false, true,"General Electric", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgeneral_electric.png?alt=media", "The company is one of the largest and most diversified industrial corporations in the world and is engaged in the developing and manufacturing of a wide range of products spanning various industries.","Stocks");
    private SymbolsData honeywell = new SymbolsData(false, true,"Honeywell", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fhoneywell.png?alt=media", "The company is engaged in the manufacturing of aerospace products, control sensing products and other technological solutions and services.","Stocks");
    private SymbolsData lockheed_martin = new SymbolsData(false, true,"Lockheed Martin", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Flockheedmartin.png?alt=media", "The company is a global defense and aerospace corporation involved in the design and development of advanced technology systems and other military products like the F-16 Fighting Falcon, F-22 Raptor, C-130 Hercules, the new F-35 and other.","Stocks");
    private SymbolsData lyft = new SymbolsData(false, true,"Lyft", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Flyft.png?alt=media", "The company offers customers ride sharing services in major US and Canadian cities, through its innovative mobile application.","Stocks");
    private SymbolsData raytheon = new SymbolsData(false, true,"Raytheon", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fraytheon.png?alt=media", "The company is an industrial group in the aerospace and defense industry that produces technologically advanced products like integrated air and missile defense systems, electronic warfare solutions and other.","Stocks");
    private SymbolsData uber_technologies_inc = new SymbolsData(false, true,"Uber Technologies Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fuber.png?alt=media", "The company offers customers ride sharing services in six continents, through its innovative platform and mobile application.","Stocks");
    private SymbolsData emerson_electric = new SymbolsData(false, true,"Emerson Electric", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Femerson_electric.png?alt=media", "The company designs and manufactures electronic and electrical equipment, software, systems, and services for a wide range of industrial and commercial end- markets.","Stocks");
    private SymbolsData equifax = new SymbolsData(false, true,"Equifax", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fequifax.png?alt=media", "The company provides information solutions, human resources and other outsourcing services to businesses, governments and consumers.","Stocks");
    private SymbolsData unilever = new SymbolsData(false, true,"Unilever", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Funilever.png?alt=media", "The company is the owner of various popular consumer product brands like Ben & Jerries, Knorr, Lipton, Dove and many more.","Stocks");
    private SymbolsData heineken_holding_nv = new SymbolsData(false, true,"Heineken Holding NV", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fheineken.png?alt=media", "The company is the producer of the worldwide famous Heineken beer brand, among other beer brands that the company produces and sells.","Stocks");
    private SymbolsData tesco = new SymbolsData(false, true,"Tesco", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftesco.jpg?alt=media", "The company operates as a food retailer, offering online retailing, brick and mortar supermarkets, and a private-label brand of products.","Stocks");
    private SymbolsData loreal = new SymbolsData(false, true,"L'Oreal", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Floreal_paris.png?alt=media", "The company develops various cosmetics products like mascara, lip gloss, foundation, eyeshadow and more, as well as skin, hair, and body care goods.","Stocks");
    private SymbolsData wm_morrison_supermarkets = new SymbolsData(false, true,"Wm Morrison Supermarkets", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FWm_morrison.png?alt=media", "The company is a British retail supermarket operator that also sells products under its own brands and offers home delivery services to its customers.","Stocks");
    private SymbolsData altria = new SymbolsData(false, true,"Altria", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Faltria.jpg?alt=media", "The company is one of the largest tobacco producers in the world and owns tobacco brands like Marlboro, Nu Mark, Nat Sherman, Middleton, Black & Mild and many other.","Stocks");
    private SymbolsData anheuser_busch_inbev_spn_adr = new SymbolsData(false, true,"Anheuser-Busch InBev - SPN ADR", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fanhenuser.png?alt=media", "The company is an international brewer and distributor of beers.","Stocks");
    private SymbolsData beyond_meat_inc = new SymbolsData(false, true,"Beyond Meat Inc", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbeyondmeat.jpg?alt=media", "The company produces various plant based products that replicate the taste, texture and smell of the original meat based products, like sausages and burgers.","Stocks");
    private SymbolsData coca_cola = new SymbolsData(false, true,"Coca Cola", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcocacola.jpg?alt=media", "The company is a beverage corporation that owns, licenses and markets non-alcoholic beverage brands, primarily sparkling beverages and a range of still beverages.","Stocks");
    private SymbolsData colgate_palmolive = new SymbolsData(false, true,"Colgate-Palmolive", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FColgate.png?alt=media", "The company is a consumer health and personal care products conglomerate involved in the production and distribution of well known products like Sanex, Palmolive, Colgate, Soupline and other.","Stocks");
    private SymbolsData costco = new SymbolsData(false, true,"Costco", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcostco.png?alt=media", "The company operates membership wholesale warehouses in the US and internationally, covering various products, like food, sundries, fresh foods and many more.","Stocks");
    private SymbolsData heinz = new SymbolsData(false, true,"Heinz", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fheinz.png?alt=media", "A food and beverage company engaged in manufacturing and marketing of food and beverage products known for its famous ketchup and mayonnaise sauces among other well known products.","Stocks");
    private SymbolsData philip_morris_int = new SymbolsData(false, true,"Philip Morris Int.", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FPhilip%20Morris%20Int.png?alt=media", "The company is a leading international tobacco company, with strong presence in 180 countries and strong tobacco brands in its portfolio of products like Phillip Morris and Marlboro cigarettes.","Stocks");
    private SymbolsData procter_and_gamble = new SymbolsData(false, true,"Procter & Gamble", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fprocter_gambler.png?alt=media", "The company owns a large portfolio with some of the worlds most recognized consumer brands in the areas of beauty, grooming, health care, home care and baby care.","Stocks");
    private SymbolsData wal_mart_stores = new SymbolsData(false, true,"Wal-Mart Stores", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fwalmart.png?alt=media", "The company operates discount stores, super-centers and neighborhood markets and is synonymous with high quality and affordable prices.","Stocks");
    private SymbolsData walgreens_boots_all = new SymbolsData(false, true,"Walgreens Boots All.", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fwalgreens_boots.png?alt=media", "The company is an international retail drug store chain, that sells pharmaceutical, personal care and cosmetics products, as well as over the counter medicines through its stores.","Stocks");
    private SymbolsData poste_italiane = new SymbolsData(false, true,"Poste italiane", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fposte%20italiane.png?alt=media", "The company is offering postal services to its customers together with a wide range of financial services such as savings accounts, insurance coverage, currency exchange services and other.","Stocks");
    private SymbolsData commerzbank = new SymbolsData(false, true,"Commerzbank", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcommerzbank.jpg?alt=media", "The company is a global provider of banking and financial services founded in 1870 with its headquarters in Frankfurt, Germany.","Stocks");
    private SymbolsData bbva = new SymbolsData(false, true,"BBVA", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FBBVA.png?alt=media", "Banco Bilbao Vizcaya Argentaria, S.A. attracts deposits and offers retail, wholesale, and investment banking services. The Bank offers consumer and mortgage loans, private banking, asset management, insurance, mutual funds, and securities brokerage services. Banco Bilbao Vizcaya Argentaria operates in Europe, Latin America, United States, China, and Turkey.","Stocks");
    private SymbolsData barclays = new SymbolsData(false, true,"Barclays", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbarclays.png?alt=media", "Barclays PLC is a global financial services provider engaged in retail banking, credit cards, wholesale banking, investment banking, wealth management, and investment management services.","Stocks");
    private SymbolsData allianz = new SymbolsData(false, true,"Allianz", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAllianz.png?alt=media", "The company is an insurance company offering a variety of property and casualty, life and health insurance services to its customers, as well as fund management services.","Stocks");
    private SymbolsData bank_of_america = new SymbolsData(false, true,"Bank of America", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FBank_of_america.png?alt=media", "The company is a multinational banking group that offers clients personal, corporate and investment banking services as well as asset management solutions.","Stocks");
    private SymbolsData citiGroup = new SymbolsData(false, true,"CitiGroup", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fciti_group.png?alt=media", "The company is a multinational banking group that offers clients personal, corporate and investment banking services as well as asset management solutions.","Stocks");
    private SymbolsData discover_financial_services = new SymbolsData(false, true,"Discover Financial Services", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdiscover_financial_services.png?alt=media", "A direct banking and payment services company offering clients credit card loans, student and personal loans, home equity loans and deposit products.","Stocks");
    private SymbolsData etrade = new SymbolsData(false, true,"E-Trade", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FE-trade.png?alt=media", "The company is an online discount stock brokerage firm that offers its clients the ability to trade various financial instruments through its online platform, among other services.","Stocks");
    private SymbolsData fifth_third_bank = new SymbolsData(false, true,"Fifth Third Bank", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffifth_third_bank.png?alt=media", "A bank holding company involved in retail and commercial banking, investment services and other financial services.","Stocks");
    private SymbolsData goldman_sachs = new SymbolsData(false, true,"Goldman Sachs", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fgoldmansachas.png?alt=media", "The company is a multinational investment banking group that offers clients corporate and investment banking services as well as asset management solutions.","Stocks");
    private SymbolsData jp_morgan_chase = new SymbolsData(false, true,"JP Morgan chase", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fjpmorgan.png?alt=media", "The company is a multinational banking group that offers clients personal, corporate and investment banking services as well as asset management solutions.","Stocks");
    private SymbolsData morgan_stanley = new SymbolsData(false, true,"Morgan Stanley", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fmorganstanley.png?alt=media", "The company is a multinational banking group that offers clients personal, corporate and investment banking services as well as asset management solutions.","Stocks");
    private SymbolsData truist_financial_corp = new SymbolsData(false, true,"Truist Financial Corp.", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftruist.png?alt=media", "The company is involved in the provision of a wide range of financial services covering from retail commercial banking to institutional banking, asset management and many more.","Stocks");
    private SymbolsData chevron = new SymbolsData(false, true,"Chevron", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fchevron.png?alt=media", "The world’s fourth-largest oil integrated company and second largest US company based on market cap and proven reserves.","Stocks");
    private SymbolsData concho_resources = new SymbolsData(false, true,"Concho Resources", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fconcho.jpg?alt=media", "An independent oil and natural gas company engaged in the acquisition, development, exploration and production of oil and natural gas properties.","Stocks");
    private SymbolsData conocoPhillips = new SymbolsData(false, true,"ConocoPhillips", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fconoco.png?alt=media", "The company is an independent exploration and production company for crude oil, bitumen, natural gas, liquefied natural gas and natural gas liquids.","Stocks");
    private SymbolsData devon_energy = new SymbolsData(false, true,"Devon Energy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdevon.png?alt=media", "The company is a leading independent oil and natural gas exploration and production corporation.","Stocks");
    private SymbolsData diamond_offshore_drilling = new SymbolsData(false, true,"Diamond Offshore Drilling", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fdiamond_offshore.png?alt=media", "A global offshore oil and gas drilling contractor operating in deep water, harsh environment, conventional semi-submersible, and jack-up markets.","Stocks");
    private SymbolsData schlumberger = new SymbolsData(false, true,"Schlumberger", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fschlumberger.png?alt=media", "The company is the world's largest oilfield services provider of technological solutions for oil drilling, production and processing in the oil and gas industry.","Stocks");
    private SymbolsData eqt_corporation = new SymbolsData(false, true,"EQT Corporation", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Feqt.png?alt=media", "The company is an integrated oil and gas energy group involved in the gathering, production and distribution of oil and gas.","Stocks");
    private SymbolsData exxon_mobil = new SymbolsData(false, true,"Exxon Mobil", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FExxon%20Mobil.png?alt=media", "The company is one of the leading oil and gas companies in the world and is involved in the exploration, production, transportation and sale of crude oil and related products.","Stocks");
    private SymbolsData suncor_energy_inc = new SymbolsData(false, true,"Suncor Energy Inc.", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fsuncor.png?alt=media", "The company is a Canadian oil and gas producer with operations covering exploration, production, refining and marketing.","Stocks");
    private SymbolsData consolidated_edison = new SymbolsData(false, true,"Consolidated Edison", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fconsolidat_ededison.jpg?alt=media", "The company is one of the largest US electricity and natural gas utility companies and operates one of the largest and most complex energy delivery systems in the world with decades of experience.","Stocks");
    private SymbolsData dte_energy = new SymbolsData(false, true,"DTE Energy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FDte energy.png?alt=media", "The company is an electricity and natural gas utility that generates electricity and distributes it to customers, together with natural gas and other related services.","Stocks");
    private SymbolsData edison = new SymbolsData(false, true,"Edison", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEdison.png?alt=media", "The company is one the largest US electric utilities and providers of industrial and commercial energy services nationwide.","Stocks");
    private SymbolsData entergy = new SymbolsData(false, true,"Entergy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEntergy.png?alt=media", "The company is a US utility company involved in electric power production and retail electricity distribution.","Stocks");
    private SymbolsData firstEnergy = new SymbolsData(false, true,"FirstEnergy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffirst_enegry.png?alt=media", "The company is a diversified energy utility corporation involved in the generation and distribution of electricity, as well as other energy-related services.","Stocks");
    private SymbolsData nextEra_energy = new SymbolsData(false, true,"NextEra Energy", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fnextera.png?alt=media", "The company is a leading energy corporation that generates and distributes energy.","Stocks");
    private SymbolsData eon = new SymbolsData(false, true,"E.ON", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Feon.png?alt=media", "The company is one of the largest utility companies in the world and is headquartered in Germany with its stock trading on various stock exchanges around the world.","Stocks");
    private SymbolsData telefonica = new SymbolsData(false, true,"Telefonica", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftelefonica.png?alt=media", "The company is a Spanish multinational integrated telecommunications group offering data, telephone and mobile services to its customers.","Stocks");
    private SymbolsData telecom_italia = new SymbolsData(false, true,"Telecom Italia", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ftelecomitalia.png?alt=media", "The company is an Italian telecommunications corporation that offers its customers telephony services, mobile and DSL data services.","Stocks");
    private SymbolsData at_and_t = new SymbolsData(false, true,"AT&T", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FAT&T.jpg?alt=media", "The company is one of the largest providers of communications and digital entertainment services in the United States and worldwide.","Stocks");
    private SymbolsData vodafone_group_plc = new SymbolsData(false, true,"Vodafone Group PLC", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fvodafone_group.png?alt=media", "Vodafone Group is a British telecommunications company, with headquarters in London and offices around the world. It predominantly operates services in the regions of Asia, Africa, Europe, and Oceania.","Stocks");
    private SymbolsData centuryLink = new SymbolsData(false, true,"CenturyLink", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fcenturylink.png?alt=media", "The company is an integrated communications company serving residential and business customers.","Stocks");
    private SymbolsData tmobile_us_inc = new SymbolsData(false, true,"T-Mobile US, Inc.",time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FT_mobile_us.png?alt=media", "The company is a national wireless communication services corporation that also provides devices and accessories across its brands, T-Mobile and MetroPCS.","Stocks");
    private SymbolsData verizon = new SymbolsData(false, true,"Verizon", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fverizon.png?alt=media", "The company is an international telecommunication group offering its clients, wireless, data and entertainment services among other services and products.","Stocks");
    private SymbolsData bhp_billiton = new SymbolsData(false, true,"BHP Billiton", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fbhp_biliton.png?alt=media", "The company is an international miner of metals, coal and other minerals. In addition to its mining activities, the company has a strong presence in the oil and gas sector with operations in the US Gulf and Eagle Ford areas.","Stocks");
    private SymbolsData eastman_chemical = new SymbolsData(false, true,"Eastman Chemical", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEastman_chemical.png?alt=media", "A global specialty chemical company involved in the production of advanced materials, additives and specialty chemicals.","Stocks");
    private SymbolsData ecolab = new SymbolsData(false, true,"Ecolab", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fecolab.png?alt=media", "The company is an American global provider of water, hygiene and energy technologies and services to the food, energy, healthcare, industrial and hospitality markets.","Stocks");
    private SymbolsData freeport_mcmoran = new SymbolsData(false, true,"Freeport-McMoRan", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Ffreeport.jpg?alt=media", "The company is an oil and metals mining group based in the US and often called Freeport.","Stocks");
    private SymbolsData fmc_corporation = new SymbolsData(false, true,"FMC Corporation", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FFmc_corporation.png?alt=media", "The company is a leading provider of agricultural, health, nutrition and lithium technology solutions.","Stocks");
    private SymbolsData alcoa = new SymbolsData(false, true,"Alcoa", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Falcoa.png?alt=media", "Alcoa Corporation, formerly Alcoa Upstream Corporation, is engaged in the production of bauxite, alumina and aluminum of various cast and rolled products. The Company is engaged in the production and management of aluminum and alumina combined through its participation in various aspects of the industry, such as technology, mining, refining, smelting, and recycling. The Company's segments include Bauxite, Alumina, Aluminum, Cast Products, Energy and Rolled Products.","Stocks");
    private SymbolsData thyssenKrupp = new SymbolsData(false, true,"ThyssenKrupp", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fthyssenkrupp.png?alt=media", "The company is an industrial conglomerate with operations in steel manufacturing, industrial plant engineering, construction and industrial elevator production.","Stocks");
    private SymbolsData digital_realty_trust = new SymbolsData(false, true,"Digital Realty Trust", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FDigital_reality_trust.png?alt=media", "A real estate investment trust company focused on datacenter acquisition, development and operation.","Stocks");
    private SymbolsData equity_residential = new SymbolsData(false, true,"Equity Residential", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEquityResidential.jpg?alt=media", "The company is a publicly traded real estate investment trust with a focus in residential apartments.","Stocks");
    private SymbolsData essex_property_trust = new SymbolsData(false, true,"Essex Property Trust", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FEssex.png?alt=media", "The company is a real estate investment trust engaged primarily in the ownership, operation and management of apartment communities, located along the US West Coast.","Stocks");
    private SymbolsData federal_realty = new SymbolsData(false, true,"Federal Realty", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FFederal_Realty.png?alt=media", "The company is an equity real estate investment trust specialized in the ownership, management and re-development of retail and mixed-use properties in affluent communities.","Stocks");
    private SymbolsData duke_realty_corp = new SymbolsData(false, true,"Duke Realty Corp", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2Fduke_reality.png?alt=media", "The company is a real estate investment trust with a focus in industrial properties and office buildings.","Stocks");
    private SymbolsData extra_space_storage = new SymbolsData(false, true,"Extra Space Storage", time1, multiplier1, "https://firebasestorage.googleapis.com/v0/b/idnbin.appspot.com/o/uploads%2Fsymbols%2FExtra_store_storage.png?alt=media", "The company is a fully integrated, self-administered and self-managed real estate investment trust, that develops and manages self-storage properties.","Stocks");

    private ArrayList<SymbolsData> stockslist = new ArrayList<>(Arrays.asList(amd,ansys,accenture,activision_blizzard,adobe_systems,apple,autodesk,baidu,cisco_systems,
            citrix_systems,dropbox,f5_networks,facebook,fidelity_national_information_services,first_solar,fiserv,google,ibm_corporation,intel,masterCard,
            micron_technology,microsoft,nvidia,payPal,qualcomm,slack,snapchat,spotify,twitter_inc,visa,zoom_video_communications_inc,salesforce_com,juventus_football_club,
            adidas,la_francaise_des_jeux_sa,marks_spencer,continental,pirelli,advance_auto_parts,amazon,best_buy,comcast_class_a,d_r_horton,darden_restaurants,discovery_class_a,
            disney,ferrari,general_motors,hasbro,manchester_united,mcdonalds,mercadoLibre_inc,netflix,nike,pinterest_inc,starbucks,tesla,viacomCBS_inc, eBay,merck,abbVie,abbott_labs,
            align_technology,allergan,amgen,aurora_cannabis_inc,bristol_myers_squibb,cvs_health,canopy_growth_corp,cronos_group_inc,daVita,danaher,gw_pharmaceuticals_adr,
            gilead_science,medtronic,pfizer,quest_diagnostics,resmed_inc,stryker,teleflex_inc,tilray_inc_class_2_common,idexx_laboratories,easyJet, airbus_se,siemens,boeing,rolls_royce,
            m_company,caterpillar,cintas,delta_air_lines,expeditors,dover,flowserve,fortune_brands_home_and_security,general_electric,honeywell,lockheed_martin,lyft,raytheon,
            uber_technologies_inc,emerson_electric,equifax,unilever,heineken_holding_nv,tesco,loreal,wm_morrison_supermarkets,altria,anheuser_busch_inbev_spn_adr, beyond_meat_inc,coca_cola,
            colgate_palmolive,costco,heinz,philip_morris_int,procter_and_gamble,wal_mart_stores,walgreens_boots_all,poste_italiane,commerzbank,
            bbva,barclays,allianz,bank_of_america,citiGroup,discover_financial_services,etrade,fifth_third_bank,goldman_sachs,jp_morgan_chase,
            morgan_stanley,truist_financial_corp,chevron,concho_resources,conocoPhillips,devon_energy,diamond_offshore_drilling,schlumberger,eqt_corporation,
            exxon_mobil,suncor_energy_inc,consolidated_edison,dte_energy,edison,entergy,firstEnergy,nextEra_energy,eon,telefonica,telecom_italia,
            at_and_t,vodafone_group_plc,centuryLink,tmobile_us_inc,verizon,bhp_billiton,eastman_chemical,ecolab,freeport_mcmoran,fmc_corporation,alcoa,
            thyssenKrupp,digital_realty_trust,equity_residential,essex_property_trust,federal_realty,duke_realty_corp,extra_space_storage));

    public ArrayList<SymbolsData> getStockslist() {
        return stockslist;
    }
}
